### ISSUE TITLE
Abort trap: 6

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-ui#3]
After cloning and installing npm, bower, gulp, npm audit fix, etc I arrived to the steps
`gulp test` and `gulp serve`
Both gave me the same error:
```
$ gulp test
gulp[77879]: ../src/node_contextify.cc:627:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x100039393 node::Abort() [/usr/local/bin/node]
 2: 0x10003849d node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: 0x10005e5fc node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x1001fd3e7 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x1001fc704 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x1001fc141 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x96e1695c01d
 8: 0x96e1690d145
 9: 0x96e1698b900
10: 0x96e169118b5
11: 0x96e169118b5
Abort trap: 6
```

**Comment by ethansiegl** [comment]
Hello,

I just tried to reproduce your issue by pulling and starting the repository and was not able to. Do you have gulp installed globally on your machine? 

```npm install -g gulp```

**Comment by cegg** [comment]
Hi Ethan
Yes, gulp is in place but jut in case I re-ran it, here is the output 

(matchminer-ui) ~/matchminer-ui$ $ npm install -g gulp
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
+ gulp@3.9.1
updated 1 package in 2.742s

then:

(matchminer-ui) ~/matchminer-ui$ gulp test
gulp[12593]: ../src/node_contextify.cc:627:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x100039393 node::Abort() [/usr/local/bin/node]
 2: 0x10003849d node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: 0x10005e5fc node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x1001fd3e7 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x1001fc704 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x1001fc141 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x929047dc01d
 8: 0x9290478d145
 9: 0x9290480b900
10: 0x929047918b5
11: 0x929047918b5
Abort trap: 6

**Comment by ethansiegl** [comment]
Hmmm I'm not sure if being in a conda environment effects any of the gulp processes. Could you try running the commands outside the environment and see if there is any difference?

**Comment by cegg** [comment]
Tried just in bash with no conda env. Identical error.

**Comment by ethansiegl** [comment]
what version of node/npm are you using? on my machine I have node 9.10.1 and npm 5.6.0

**Comment by cegg** [comment]
my node version is v8.12.0
my npm version is 6.4.1
OS: tried both El Capitan 10.11.6 and High Sierra 10.13.6

**Comment by cegg** [comment]
I commented out line 22 in the dockerfile `RUN gulp test`
The same error about Abort Trap: 

```
matchminer-ui$ gulp test
gulp[50350]: ../src/node_contextify.cc:627:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x100039393 node::Abort() [/usr/local/bin/node]
 2: 0x10003849d node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, char const*, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: 0x10005e5fc node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x1001fd3e7 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x1001fc704 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x1001fc141 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x27913c35c01d
 8: 0x27913c30d145
 9: 0x27913c38b900
10: 0x27913c3118b5
11: 0x27913c3118b5
Abort trap: 6
```
Basically, there is the same failure from`gulp whatever` in conda env, in bash and during docker build in two different Mac OS versions - what does this point at?

**Comment by ethansiegl** [comment]
Ah, I meant after you comment out ```RUN gulp test``` and then run ```docker build .``` is there any difference? Should have been clearer..

As far as gulp goes, I'm not entirely sure why your version is so unhappy. When I run ```which gulp``` I get this: ```/Users/ethansiegel/.nvm/versions/node/v9.10.1/bin/gulp``` and my version of gulp is also 3.9.1. Is there anything different on your end?

**Comment by cegg** [comment]
With `RUN gulp test` commented out docker build succeeds.


npm WARN jit-grunt@0.9.1 requires a peer of grunt@~0.4.0 but none was installed.
npm info ok
Removing intermediate container c57342759c75
 ---> b630bd211343
Step 7/10 : COPY . /data
 ---> 788cb5ec55b9
Step 8/10 : RUN bower install --config.interactive=false  --allow-root
 ---> Running in 6fb181e10785
Removing intermediate container 6fb181e10785
 ---> f5b7e1dd43d8
Step 9/10 : WORKDIR /data
 ---> Running in 30f2aa7f8bbd
Removing intermediate container 30f2aa7f8bbd
 ---> a6f67c1d80a4
Step 10/10 : COPY dist /var/www/apache-flask/api/static
 ---> 8e068616d391
Successfully built 8e068616d391

However, `docker container ls` and `docker ps` do not find any containers.

**Comment by cegg** [comment]
As of `which gulp`, it gives this: ```
$ which gulp
/usr/local/bin/gulp
```

**Comment by ethansiegl** [comment]
I see. to start the container you need to run ```docker start [container_name]```. You can list the docker images with ```docker image ls```

**Comment by cegg** [comment]
Tried `docker build . `on El Capitan today.

It ends with:

```
Removing intermediate container cf6fa35c8dc8
 ---> 1e9f955b7e3e
Step 9/10 : WORKDIR /data
 ---> Running in be4fd4daf202
Removing intermediate container be4fd4daf202
 ---> 0427c21a80f7
Step 10/10 : COPY dist /var/www/apache-flask/api/static
 ---> 08c5f9ef619b
Successfully built 08c5f9ef619b
```

Then I check `docker container ls `
Got back empty list:
`CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES`

Just for curiosity checked aforementioned directory (STEP 10): 
```
$ ls /var/www/apache-flask/api/static
ls: /var/www/apache-flask/api/static: No such file or directory
```
So what is the way to access the newly build container?

**Comment by cegg** [comment]
Looks like I got image successfully build:

```
$ docker image ls
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
matchminer-ui                   latest              08c5f9ef619b        23 hours ago        2.12GB
```

But an atempt to start the container results in this error (both by REPOSITORY and IMAGE ID):

```
$ docker run 08c5f9ef619b
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.1
npm ERR! Linux 4.9.93-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-10-18T08_03_36_934Z-debug.log
```

**Comment by ethansiegl** [comment]
alright glad the container is up! So I think the reason the container is not starting is because you are trying to run ```npm run start``` or something like that, but the application is usually started with ```grunt serve```. If you swap out the npm command from the grunt, can you let me know what happens?

**Comment by cegg** [comment]
Sorry I am lost. The container is not up. Only the image is created. I did not get the comment about `npm run start`  and `grunt serve` .  I ran `$ docker run 08c5f9ef619b` (the id I got from `$docker image ls`). Could you explain please the connection, I never sued npm / node before.

**Comment by ethansiegl** [comment]
ah I see. sorry about that. so there are a few things going on let me try to explain as best I can. 

Earlier I was talking about adding a CMD command to the docker file to execute once the container is started. To do that you can go to the dockerfile and add ```CMD ["grunt", "serve"]``` at the very end. So then once you run```docker run [image_id]```, the image will start and (hopefully) start up the UI.

If it is not crucial to dockerize the UI at this time, I would suggest trying to get the app up and running with the API and db outside of containers first, and then coming back to containerize them afterwards since that will probably be easier

**Comment by cegg** [comment]
Thanks. OK, I tried adding `CMD ["grunt", "serve"]` to the Dockerfile. Before running another `docker build`, I install grunt globally and locally in my project (below, I hope it's the right way to do it). 
`brew install grunt`
`npm install -g grunt-cli`
`npm install grunt --save-dev`

After docker build, when I run `docker run <imageid>` I get this:
```
$ docker run 059ddd317ad4
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"grunt\": executable file not found in $PATH": unknown.
```

Adding grunt's full path to Dockerfile CMD line ( `CMD ["/usr/local/bin/grunt", "serve"]` ) and doing another docker build docker /run does not change anything, just the full path is isted in the error. I suspect it wants grunt or some part of it is not getting installed inside the docker container image.

As of not dockerized way - when I run gulp build, I get that Abort trap 6 th started this thread. 
```
$ gulp --env production build
gulp[7025]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x10003ab5a node::Abort() [/usr/local/bin/node]
 2: 0x100039bc9 node::AddEnvironmentCleanupHook(v8::Isolate*, void (*)(void*), void*) [/usr/local/bin/node]
 3: 0x10005eb02 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x1001f1089 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x1001f0324 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x1001efd60 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x19630975be3d
Abort trap: 6
```

Running $ gulp serve from my project directory gives this:
```
$ grunt serve
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
```
I wonder if all these problems happen to me because I am on MAc or maybe because I am on specific Mac OS (El Capitan)? Are you on Ubuntu ?

**Comment by cegg** [comment]
Hi Ethan,

Today I tried to docker build again and the behaviour is different. 
My `$ docker build matchminer-ui . `finished successfully. 
so I start rh container: 
`$ docker run -it matchminer-ui bash`
then I tried `$ gulp serve` - got this error:
`(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: angular is not installed. Try running `bower install``.
So I ran this:
`$ bower install --allow-root` (it won't run without --allow-root)
Got one warning, the rest went OK:  ```
Resort to using angular#1.5.5 which resolved to angular#1.5.5
Code incompatibilities may occur.
```
ran `$ gulp test`
Again, all good! (but `#RUN gulp test `in Dockerfile is commented out)
No, I try `$ gulp serve` again - it stops at the absence of something called certificates/matchminder.key:
```
$ gulp serve
[13:09:22] Using gulpfile /data/gulpfile.js
[13:09:22] Starting 'config'...
[13:09:22] Starting 'load-templates'...
[13:09:22] Starting 'scripts'...
[13:09:22] Starting 'styles'...
[13:09:23] Finished 'config' after 818 ms
[13:09:23] Finished 'load-templates' after 804 ms
[13:09:23] gulp-inject 34 files into matchminer.less.
[13:09:24] Finished 'styles' after 1.79 s
[13:09:26] all files 543.3 kB
[13:09:26] Finished 'scripts' after 3.36 s
[13:09:26] Starting 'inject'...
[13:09:26] gulp-inject 1 files into index.html.
[13:09:26] gulp-inject 92 files into index.html.
[13:09:26] Finished 'inject' after 443 ms
[13:09:26] Starting 'watch'...
[13:09:26] Finished 'watch' after 141 ms
[13:09:26] Starting 'serve'...
[13:09:26] 'serve' errored after 879 μs
[13:09:26] Error: ENOENT: no such file or directory, open '../certificates/matchminer.key'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at browserSyncInit (/data/gulp/server.js:52:12)
    at Gulp.<anonymous> (/data/gulp/server.js:100:2)
    at module.exports (/data/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/data/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/data/node_modules/orchestrator/index.js:214:10)
    at /data/node_modules/orchestrator/index.js:279:18
    at finish (/data/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/data/node_modules/orchestrator/lib/runTask.js:60:3)
    at Gulp.Orchestrator._runTask (/data/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/data/node_modules/orchestrator/index.js:214:10)
    at /data/node_modules/orchestrator/index.js:279:18
    at finish (/data/node_modules/orchestrator/lib/runTask.js:21:8)
    at /data/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/data/node_modules/end-of-stream/node_modules/once/once.js:17:25)
```
It does not go back to the command line prompt, just hangs there. 
And the site is not available at http://localhost:8001, and there's nothing on ports 5555 or 9200 either.

**Comment by cegg** [comment]
Some update: the error about "Abort trap 6" goes away if I run this : `$ npm i natives` Just fond it in some forum, no idea how it fixes the problem. Maybe this can be closed. I am going to open a new issue for the next failure in a minute.
