### ISSUE TITLE
gulp serve: complain about Protocol "http:" not supported

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-ui#7]
After cloning and building matchminer-ui once I run gulp server the web server starts successfully on port 8001. However, there is an error in the server output, most likely some required configuration is missing:

```
host011:/Users/ipozdnya/matchminer-ui$ gulp serve
[18:25:56] Using gulpfile ~/matchminer-ui/gulpfile.js
[18:25:56] Starting 'config'...
[18:25:56] Starting 'load-templates'...
[18:25:56] Starting 'scripts'...
[18:25:57] Starting 'styles'...
[18:25:58] Finished 'load-templates' after 1.68 s
[18:25:58] Finished 'config' after 1.7 s
[18:25:58] gulp-inject 34 files into matchminer.less.
[18:25:59] Finished 'styles' after 2.61 s
[18:26:01] all files 543.28 kB
[18:26:01] Finished 'scripts' after 4.16 s
[18:26:01] Starting 'inject'...
[18:26:01] gulp-inject 1 files into index.html.
[18:26:01] gulp-inject 92 files into index.html.
[18:26:01] Finished 'inject' after 424 ms
[18:26:01] Starting 'watch'...
[18:26:01] Finished 'watch' after 278 ms
[18:26:01] Starting 'serve'...
[HPM] Proxy created: /api  ->  http://localhost:5555
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[HPM] Proxy created: /elasticsearch  ->  http://localhost:9200
[HPM] Proxy rewrite rule created: "^/elasticsearch" ~> ""
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[18:26:01] Finished 'serve' after 80 ms
[BrowserSync SPA] Running...
[Browsersync] Access URLs:
 ---------------------------------------
       Local: http://localhost:8001/
    External: http://146.247.18.11:8001/
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ---------------------------------------
[Browsersync] Serving files from: .tmp/serve
[Browsersync] Serving files from: app
[HPM] GET /api/user/577cf6ef2b9920002cef0337?cacheBuster=1546622763223 -> http://localhost:5555
TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
    at new ClientRequest (_http_client.js:118:11)
    at Object.request (http.js:41:10)
    at Array.stream (/Users/ipozdnya/matchminer-ui/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:111:74)
    at ProxyServer.<anonymous> (/Users/ipozdnya/matchminer-ui/node_modules/http-proxy/lib/http-proxy/index.js:80:21)
    at middleware (/Users/ipozdnya/matchminer-ui/node_modules/http-proxy-middleware/lib/index.js:43:19)
    at call (/Users/ipozdnya/matchminer-ui/node_modules/connect/index.js:239:7)
    at next (/Users/ipozdnya/matchminer-ui/node_modules/connect/index.js:183:5)
    at middleware (/Users/ipozdnya/matchminer-ui/node_modules/http-proxy-middleware/lib/index.js:45:13)
    at call (/Users/ipozdnya/matchminer-ui/node_modules/connect/index.js:239:7)
    at next (/Users/ipozdnya/matchminer-ui/node_modules/connect/index.js:183:5)
    at /Users/ipozdnya/matchminer-ui/node_modules/connect-modrewrite/index.js:129:7
    at call (/Users/ipozdnya/matchminer-ui/node_modules/connect/index.js:239:7)
    at next (/Users/ipozdnya/matchminer-ui/node_modules/connect/index.js:183:5)
    at next (/Users/ipozdnya/matchminer-ui/node_modules/connect/index.js:161:14)
    at next (/Users/ipozdnya/matchminer-ui/node_modules/connect/index.js:161:14)
    at respModifierMiddleware (/Users/ipozdnya/matchminer-ui/node_modules/resp-modifier/index.js:73:28)
[HPM] GET /api/user/577cf6ef2b9920002cef0337?cacheBuster=1546622763223 -> http://localhost:5555
```

**Comment by ethansiegl** [comment]
Is this still an issue? I am unable to replicate..

**Comment by cegg** [comment]
Yes I have not resolved it. on `$gulp serve` I get that 

> "TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:""
message. 

I can't tell how critical it is, the site gets open on the browser at http://localhost:8001/#/ with "Internal Server Error" non-editable fields. I suspect it's important.

When I insect the page with browser developer's tools, I see failed ajax calls (status 500 ) like this:
`http://localhost:8001/api/public_stats?cacheBuster=1547638332980`
If I try to call that, I get that https error again:

> TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
>    at new ClientRequest (_http_client.js:131:11)

There might be differences in the way our machines setup in terms of http and https? When you get the frontpage open with BrowserSync, are you in https or http? Also: what's your default browser just in case?

Can I send you couple of screenshots, maybe it will be obvious right away?

Thanks!

**Comment by ethansiegl** [comment]
ah i see. this is an issue with your frontend proxy. It is trying to send to https://localhost instead of http://localhost. 

I've been able to replicate this issue and solve by commenting out line 48 in `gulp/server/js`. Can you let me know if that works? Copied below for reference 

`var matchMinerProxy = proxy('/api', {
		target: config[environment].ENV.api.host,
		changeOrigin: true,
		logLevel: 'debug',
		// agent: https.globalAgent,
		secure: true,
		https: true,
		ssl: {
			key: fs.readFileSync(config[environment].ENV.certificate.key, 'utf8'),
			cert: fs.readFileSync(config[environment].ENV.certificate.cert, 'utf8')
		}
	});
`

**Comment by cegg** [comment]
Thanks, commenting out the agent line does eliminate that complain about http vs https! 

However, after that I hit the next error (probably also config item), about something on port 5555
(and the interface that opens in the browser is still broken with "Internal server error" and non-editable fields):
 
```
$ gulp serve

[17:52:35] Using gulpfile ~/matchminer-ui/gulpfile.js
[17:52:35] Starting 'config'...
[17:52:35] Starting 'load-templates'...
[17:52:35] Starting 'scripts'...
[17:52:38] Starting 'styles'...
[17:52:42] Finished 'config' after 7.57 s
[17:52:42] Finished 'load-templates' after 7.52 s
[17:52:43] gulp-inject 34 files into matchminer.less.
[17:52:45] Finished 'styles' after 7.11 s
[17:52:46] all files 543.28 kB
[17:52:46] Finished 'scripts' after 11 s
[17:52:46] Starting 'inject'...
[17:52:46] gulp-inject 1 files into index.html.
[17:52:47] gulp-inject 92 files into index.html.
[17:52:47] Finished 'inject' after 617 ms
[17:52:47] Starting 'watch'...
[17:52:47] Finished 'watch' after 158 ms
[17:52:47] Starting 'serve'...
[HPM] Proxy created: /api  ->  http://localhost:5555
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[HPM] Proxy created: /elasticsearch  ->  http://localhost:9200
[HPM] Proxy rewrite rule created: "^/elasticsearch" ~> ""
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[17:52:47] Finished 'serve' after 352 ms
[BrowserSync SPA] Running...
[Browsersync] Access URLs:
 ------------------------------------
    Local: http://localhost:8001/
 External: http://146.247.18.11:8001/
 ------------------------------------
[Browsersync] Serving files from: .tmp/serve
[Browsersync] Serving files from: app
[HPM] GET /api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657569705 -> http://localhost:5555
[HPM] PROXY ERROR: ECONNREFUSED. localhost:8001 -> http://localhost:5555/api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657569705
[HPM] GET /api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657569705 -> http://localhost:5555
[HPM] PROXY ERROR: ECONNREFUSED. localhost:8001 -> http://localhost:5555/api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657569705
[HPM] GET /api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657570626 -> http://localhost:5555
[HPM] PROXY ERROR: ECONNREFUSED. localhost:8001 -> http://localhost:5555/api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657570626
[HPM] GET /api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657570626 -> http://localhost:5555
[HPM] PROXY ERROR: ECONNREFUSED. localhost:8001 -> http://localhost:5555/api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657570626
[HPM] GET /api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657570626 -> http://localhost:5555
[HPM] PROXY ERROR: ECONNREFUSED. localhost:8001 -> http://localhost:5555/api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657570626
[HPM] GET /api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657570626 -> http://localhost:5555
[HPM] PROXY ERROR: ECONNREFUSED. localhost:8001 -> http://localhost:5555/api/user/577cf6ef2b9920002cef0337?cacheBuster=1547657570626
[HPM] GET /api/public_stats?cacheBuster=1547657570910 -> http://localhost:5555
[HPM] PROXY ERROR: ECONNREFUSED. localhost:8001 -> http://localhost:5555/api/public_stats?cacheBuster=1547657570910
```

**Comment by ethansiegl** [comment]
what port is your local api running on? whatever it is should correspond to the port in the `properties/config.json` file

**Comment by ethansiegl** [comment]
so the API error looks like a database refused connection. Do you have a local instance of MongoDB communicating with your API correctly?

```
docker run --name match-mongo -d -p 27017:27017 mongo mongod --smallfiles --replSet=rs0
docker exec -it match-mongo mongo matchminer --eval "rs.initiate();"
```

See the matchminer-api [readme](https://github.com/dfci/matchminer-api) for more explanation re: the db...

As far as the UI error goes, you must make sure that the API port that is used when serving matches the api port specified in the ui `config.json` file. It looks like you have a mismatch here, where your UI is looking for port 5555, and your API is served on 5000. If you change one of those configs to match the other, you might have better luck

**Comment by cegg** [comment]
Hi Ethan,
I got all 3 pieces to talk to each other, I hope I documented all the adjustments, later I will share with you. No, the port had to stay 5000 but your suggestion to get one ajax call in browser helped  me to get it to work step-by-step, thanks!
The frontpage now loads with numbers of patients and trials. However, attempt to type any char in the search fields results in another broken Ajax call like this:
http://localhost:8001/elasticsearch/matchminer/trial/_search
Hitting that in a browser gives this:
```
{
error: {
root_cause: [
{
type: "index_not_found_exception",
reason: "no such index",
resource.type: "index_or_alias",
resource.id: "matchminer",
index_uuid: "_na_",
index: "matchminer"
}
],
type: "index_not_found_exception",
reason: "no such index",
resource.type: "index_or_alias",
resource.id: "matchminer",
index_uuid: "_na_",
index: "matchminer"
},
status: 404
}
```
I guess I have to figure out elasticsearch config now

Igor

**Comment by cegg** [comment]
I resolved that `index_not_found_exception` error by creating index in mongo. 
```
> use admin 
> db.createUser({     user:"admin",     pwd:"abc123",     roles:[{role:"userAdminAnyDatabase",db:"admin"}],     passwordDigestor:"server" })
```
Is this how it's meant to be created?

**Comment by ethansiegl** [comment]
that's odd. the index not found exception is I think looking for an elasticsearch index which you would create with a curl or requests command.. 

```
curl -XPOST http://yourelasticsearchlocation:9200/matchminer
```

to create an index named matchminer. is this still an issue for you?
